/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as AuthenticatedBarbershopsIndexRouteImport } from './routes/_authenticated/barbershops/index'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants/index'
import { Route as AuthenticatedBarbershopsTenantIdIndexRouteImport } from './routes/_authenticated/barbershops/$tenantId/index'
import { Route as AuthenticatedSupportContextIdIndexRouteImport } from './routes/_authenticated/support/$contextId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBarbershopsIndexRoute =
  AuthenticatedBarbershopsIndexRouteImport.update({
    id: '/barbershops/',
    path: '/barbershops/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBarbershopsTenantIdIndexRoute =
  AuthenticatedBarbershopsTenantIdIndexRouteImport.update({
    id: '/barbershops/$tenantId/',
    path: '/barbershops/$tenantId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportContextIdIndexRoute =
  AuthenticatedSupportContextIdIndexRouteImport.update({
    id: '/support/$contextId/',
    path: '/support/$contextId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/barbershops/': typeof AuthenticatedBarbershopsIndexRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/barbershops/$tenantId/': typeof AuthenticatedBarbershopsTenantIdIndexRoute
  '/support/$contextId/': typeof AuthenticatedSupportContextIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/barbershops': typeof AuthenticatedBarbershopsIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/barbershops/$tenantId': typeof AuthenticatedBarbershopsTenantIdIndexRoute
  '/support/$contextId': typeof AuthenticatedSupportContextIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/_authenticated/barbershops/': typeof AuthenticatedBarbershopsIndexRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/barbershops/$tenantId/': typeof AuthenticatedBarbershopsTenantIdIndexRoute
  '/_authenticated/support/$contextId/': typeof AuthenticatedSupportContextIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/barbershops/'
    | '/tenants/'
    | '/barbershops/$tenantId/'
    | '/support/$contextId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/barbershops'
    | '/tenants'
    | '/barbershops/$tenantId'
    | '/support/$contextId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/_authenticated/barbershops/'
    | '/_authenticated/tenants/'
    | '/_authenticated/barbershops/$tenantId/'
    | '/_authenticated/support/$contextId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/barbershops/': {
      id: '/_authenticated/barbershops/'
      path: '/barbershops'
      fullPath: '/barbershops/'
      preLoaderRoute: typeof AuthenticatedBarbershopsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/barbershops/$tenantId/': {
      id: '/_authenticated/barbershops/$tenantId/'
      path: '/barbershops/$tenantId'
      fullPath: '/barbershops/$tenantId/'
      preLoaderRoute: typeof AuthenticatedBarbershopsTenantIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/$contextId/': {
      id: '/_authenticated/support/$contextId/'
      path: '/support/$contextId'
      fullPath: '/support/$contextId/'
      preLoaderRoute: typeof AuthenticatedSupportContextIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBarbershopsIndexRoute: typeof AuthenticatedBarbershopsIndexRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
  AuthenticatedBarbershopsTenantIdIndexRoute: typeof AuthenticatedBarbershopsTenantIdIndexRoute
  AuthenticatedSupportContextIdIndexRoute: typeof AuthenticatedSupportContextIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBarbershopsIndexRoute: AuthenticatedBarbershopsIndexRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
  AuthenticatedBarbershopsTenantIdIndexRoute:
    AuthenticatedBarbershopsTenantIdIndexRoute,
  AuthenticatedSupportContextIdIndexRoute:
    AuthenticatedSupportContextIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
