/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as WorkspacePreviewIndexRouteImport } from './routes/workspace-preview/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as WorkspacePreviewFormsRouteRouteImport } from './routes/workspace-preview/forms/route'
import { Route as WorkspacePreviewFormsIndexRouteImport } from './routes/workspace-preview/forms/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPreferencesIndexRouteImport } from './routes/_authenticated/preferences/index'
import { Route as AuthenticatedOverviewIndexRouteImport } from './routes/_authenticated/overview/index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as WorkspacePreviewFormsWarehousesIndexRouteImport } from './routes/workspace-preview/forms/warehouses/index'
import { Route as WorkspacePreviewFormsTrucksIndexRouteImport } from './routes/workspace-preview/forms/trucks/index'
import { Route as WorkspacePreviewFormsProductsIndexRouteImport } from './routes/workspace-preview/forms/products/index'
import { Route as WorkspacePreviewFormsPermissionProfilesIndexRouteImport } from './routes/workspace-preview/forms/permission-profiles/index'
import { Route as WorkspacePreviewFormsDriversIndexRouteImport } from './routes/workspace-preview/forms/drivers/index'
import { Route as WorkspacePreviewFormsCustomersIndexRouteImport } from './routes/workspace-preview/forms/customers/index'
import { Route as WorkspacePreviewFormsCompaniesIndexRouteImport } from './routes/workspace-preview/forms/companies/index'
import { Route as WorkspacePreviewFormsCollaboratorsIndexRouteImport } from './routes/workspace-preview/forms/collaborators/index'
import { Route as AuthenticatedUsersPermissionProfilesIndexRouteImport } from './routes/_authenticated/users/permission-profiles/index'
import { Route as AuthenticatedUsersListIndexRouteImport } from './routes/_authenticated/users/list/index'
import { Route as AuthenticatedUsersInvitationsIndexRouteImport } from './routes/_authenticated/users/invitations/index'
import { Route as AuthenticatedUsersCollaboratorsIndexRouteImport } from './routes/_authenticated/users/collaborators/index'
import { Route as AuthenticatedInventoryWarehousesIndexRouteImport } from './routes/_authenticated/inventory/warehouses/index'
import { Route as AuthenticatedInventoryProductsIndexRouteImport } from './routes/_authenticated/inventory/products/index'
import { Route as AuthenticatedFleetTrucksIndexRouteImport } from './routes/_authenticated/fleet/trucks/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacePreviewIndexRoute = WorkspacePreviewIndexRouteImport.update({
  id: '/workspace-preview/',
  path: '/workspace-preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WorkspacePreviewFormsRouteRoute =
  WorkspacePreviewFormsRouteRouteImport.update({
    id: '/workspace-preview/forms',
    path: '/workspace-preview/forms',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacePreviewFormsIndexRoute =
  WorkspacePreviewFormsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreferencesIndexRoute =
  AuthenticatedPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewIndexRoute =
  AuthenticatedOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/drivers/index.lazy').then((d) => d.Route),
  )
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/customers/index.lazy').then((d) => d.Route),
  )
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/companies/index.lazy').then((d) => d.Route),
  )
const WorkspacePreviewFormsWarehousesIndexRoute =
  WorkspacePreviewFormsWarehousesIndexRouteImport.update({
    id: '/warehouses/',
    path: '/warehouses/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any).lazy(() =>
    import('./routes/workspace-preview/forms/warehouses/index.lazy').then(
      (d) => d.Route,
    ),
  )
const WorkspacePreviewFormsTrucksIndexRoute =
  WorkspacePreviewFormsTrucksIndexRouteImport.update({
    id: '/trucks/',
    path: '/trucks/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any).lazy(() =>
    import('./routes/workspace-preview/forms/trucks/index.lazy').then(
      (d) => d.Route,
    ),
  )
const WorkspacePreviewFormsProductsIndexRoute =
  WorkspacePreviewFormsProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any).lazy(() =>
    import('./routes/workspace-preview/forms/products/index.lazy').then(
      (d) => d.Route,
    ),
  )
const WorkspacePreviewFormsPermissionProfilesIndexRoute =
  WorkspacePreviewFormsPermissionProfilesIndexRouteImport.update({
    id: '/permission-profiles/',
    path: '/permission-profiles/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any).lazy(() =>
    import('./routes/workspace-preview/forms/permission-profiles/index.lazy').then(
      (d) => d.Route,
    ),
  )
const WorkspacePreviewFormsDriversIndexRoute =
  WorkspacePreviewFormsDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any).lazy(() =>
    import('./routes/workspace-preview/forms/drivers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const WorkspacePreviewFormsCustomersIndexRoute =
  WorkspacePreviewFormsCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any).lazy(() =>
    import('./routes/workspace-preview/forms/customers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const WorkspacePreviewFormsCompaniesIndexRoute =
  WorkspacePreviewFormsCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any).lazy(() =>
    import('./routes/workspace-preview/forms/companies/index.lazy').then(
      (d) => d.Route,
    ),
  )
const WorkspacePreviewFormsCollaboratorsIndexRoute =
  WorkspacePreviewFormsCollaboratorsIndexRouteImport.update({
    id: '/collaborators/',
    path: '/collaborators/',
    getParentRoute: () => WorkspacePreviewFormsRouteRoute,
  } as any).lazy(() =>
    import('./routes/workspace-preview/forms/collaborators/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUsersPermissionProfilesIndexRoute =
  AuthenticatedUsersPermissionProfilesIndexRouteImport.update({
    id: '/users/permission-profiles/',
    path: '/users/permission-profiles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/permission-profiles/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedUsersListIndexRoute =
  AuthenticatedUsersListIndexRouteImport.update({
    id: '/users/list/',
    path: '/users/list/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersInvitationsIndexRoute =
  AuthenticatedUsersInvitationsIndexRouteImport.update({
    id: '/users/invitations/',
    path: '/users/invitations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersCollaboratorsIndexRoute =
  AuthenticatedUsersCollaboratorsIndexRouteImport.update({
    id: '/users/collaborators/',
    path: '/users/collaborators/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/collaborators/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedInventoryWarehousesIndexRoute =
  AuthenticatedInventoryWarehousesIndexRouteImport.update({
    id: '/inventory/warehouses/',
    path: '/inventory/warehouses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/inventory/warehouses/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedInventoryProductsIndexRoute =
  AuthenticatedInventoryProductsIndexRouteImport.update({
    id: '/inventory/products/',
    path: '/inventory/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/inventory/products/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedFleetTrucksIndexRoute =
  AuthenticatedFleetTrucksIndexRouteImport.update({
    id: '/fleet/trucks/',
    path: '/fleet/trucks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/fleet/trucks/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/workspace-preview/forms': typeof WorkspacePreviewFormsRouteRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/workspace-preview/': typeof WorkspacePreviewIndexRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/drivers/': typeof AuthenticatedDriversIndexRoute
  '/overview/': typeof AuthenticatedOverviewIndexRoute
  '/preferences/': typeof AuthenticatedPreferencesIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/workspace-preview/forms/': typeof WorkspacePreviewFormsIndexRoute
  '/fleet/trucks/': typeof AuthenticatedFleetTrucksIndexRoute
  '/inventory/products/': typeof AuthenticatedInventoryProductsIndexRoute
  '/inventory/warehouses/': typeof AuthenticatedInventoryWarehousesIndexRoute
  '/users/collaborators/': typeof AuthenticatedUsersCollaboratorsIndexRoute
  '/users/invitations/': typeof AuthenticatedUsersInvitationsIndexRoute
  '/users/list/': typeof AuthenticatedUsersListIndexRoute
  '/users/permission-profiles/': typeof AuthenticatedUsersPermissionProfilesIndexRoute
  '/workspace-preview/forms/collaborators/': typeof WorkspacePreviewFormsCollaboratorsIndexRoute
  '/workspace-preview/forms/companies/': typeof WorkspacePreviewFormsCompaniesIndexRoute
  '/workspace-preview/forms/customers/': typeof WorkspacePreviewFormsCustomersIndexRoute
  '/workspace-preview/forms/drivers/': typeof WorkspacePreviewFormsDriversIndexRoute
  '/workspace-preview/forms/permission-profiles/': typeof WorkspacePreviewFormsPermissionProfilesIndexRoute
  '/workspace-preview/forms/products/': typeof WorkspacePreviewFormsProductsIndexRoute
  '/workspace-preview/forms/trucks/': typeof WorkspacePreviewFormsTrucksIndexRoute
  '/workspace-preview/forms/warehouses/': typeof WorkspacePreviewFormsWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/workspace-preview': typeof WorkspacePreviewIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/overview': typeof AuthenticatedOverviewIndexRoute
  '/preferences': typeof AuthenticatedPreferencesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workspace-preview/forms': typeof WorkspacePreviewFormsIndexRoute
  '/fleet/trucks': typeof AuthenticatedFleetTrucksIndexRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsIndexRoute
  '/inventory/warehouses': typeof AuthenticatedInventoryWarehousesIndexRoute
  '/users/collaborators': typeof AuthenticatedUsersCollaboratorsIndexRoute
  '/users/invitations': typeof AuthenticatedUsersInvitationsIndexRoute
  '/users/list': typeof AuthenticatedUsersListIndexRoute
  '/users/permission-profiles': typeof AuthenticatedUsersPermissionProfilesIndexRoute
  '/workspace-preview/forms/collaborators': typeof WorkspacePreviewFormsCollaboratorsIndexRoute
  '/workspace-preview/forms/companies': typeof WorkspacePreviewFormsCompaniesIndexRoute
  '/workspace-preview/forms/customers': typeof WorkspacePreviewFormsCustomersIndexRoute
  '/workspace-preview/forms/drivers': typeof WorkspacePreviewFormsDriversIndexRoute
  '/workspace-preview/forms/permission-profiles': typeof WorkspacePreviewFormsPermissionProfilesIndexRoute
  '/workspace-preview/forms/products': typeof WorkspacePreviewFormsProductsIndexRoute
  '/workspace-preview/forms/trucks': typeof WorkspacePreviewFormsTrucksIndexRoute
  '/workspace-preview/forms/warehouses': typeof WorkspacePreviewFormsWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/workspace-preview/forms': typeof WorkspacePreviewFormsRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/workspace-preview/': typeof WorkspacePreviewIndexRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/overview/': typeof AuthenticatedOverviewIndexRoute
  '/_authenticated/preferences/': typeof AuthenticatedPreferencesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/workspace-preview/forms/': typeof WorkspacePreviewFormsIndexRoute
  '/_authenticated/fleet/trucks/': typeof AuthenticatedFleetTrucksIndexRoute
  '/_authenticated/inventory/products/': typeof AuthenticatedInventoryProductsIndexRoute
  '/_authenticated/inventory/warehouses/': typeof AuthenticatedInventoryWarehousesIndexRoute
  '/_authenticated/users/collaborators/': typeof AuthenticatedUsersCollaboratorsIndexRoute
  '/_authenticated/users/invitations/': typeof AuthenticatedUsersInvitationsIndexRoute
  '/_authenticated/users/list/': typeof AuthenticatedUsersListIndexRoute
  '/_authenticated/users/permission-profiles/': typeof AuthenticatedUsersPermissionProfilesIndexRoute
  '/workspace-preview/forms/collaborators/': typeof WorkspacePreviewFormsCollaboratorsIndexRoute
  '/workspace-preview/forms/companies/': typeof WorkspacePreviewFormsCompaniesIndexRoute
  '/workspace-preview/forms/customers/': typeof WorkspacePreviewFormsCustomersIndexRoute
  '/workspace-preview/forms/drivers/': typeof WorkspacePreviewFormsDriversIndexRoute
  '/workspace-preview/forms/permission-profiles/': typeof WorkspacePreviewFormsPermissionProfilesIndexRoute
  '/workspace-preview/forms/products/': typeof WorkspacePreviewFormsProductsIndexRoute
  '/workspace-preview/forms/trucks/': typeof WorkspacePreviewFormsTrucksIndexRoute
  '/workspace-preview/forms/warehouses/': typeof WorkspacePreviewFormsWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace-preview/forms'
    | '/login/'
    | '/workspace-preview/'
    | '/companies/'
    | '/customers/'
    | '/drivers/'
    | '/overview/'
    | '/preferences/'
    | '/profile/'
    | '/users/'
    | '/workspace-preview/forms/'
    | '/fleet/trucks/'
    | '/inventory/products/'
    | '/inventory/warehouses/'
    | '/users/collaborators/'
    | '/users/invitations/'
    | '/users/list/'
    | '/users/permission-profiles/'
    | '/workspace-preview/forms/collaborators/'
    | '/workspace-preview/forms/companies/'
    | '/workspace-preview/forms/customers/'
    | '/workspace-preview/forms/drivers/'
    | '/workspace-preview/forms/permission-profiles/'
    | '/workspace-preview/forms/products/'
    | '/workspace-preview/forms/trucks/'
    | '/workspace-preview/forms/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workspace-preview'
    | '/companies'
    | '/customers'
    | '/drivers'
    | '/overview'
    | '/preferences'
    | '/profile'
    | '/users'
    | '/workspace-preview/forms'
    | '/fleet/trucks'
    | '/inventory/products'
    | '/inventory/warehouses'
    | '/users/collaborators'
    | '/users/invitations'
    | '/users/list'
    | '/users/permission-profiles'
    | '/workspace-preview/forms/collaborators'
    | '/workspace-preview/forms/companies'
    | '/workspace-preview/forms/customers'
    | '/workspace-preview/forms/drivers'
    | '/workspace-preview/forms/permission-profiles'
    | '/workspace-preview/forms/products'
    | '/workspace-preview/forms/trucks'
    | '/workspace-preview/forms/warehouses'
  id:
    | '__root__'
    | '/_authenticated'
    | '/workspace-preview/forms'
    | '/_authenticated/'
    | '/login/'
    | '/workspace-preview/'
    | '/_authenticated/companies/'
    | '/_authenticated/customers/'
    | '/_authenticated/drivers/'
    | '/_authenticated/overview/'
    | '/_authenticated/preferences/'
    | '/_authenticated/profile/'
    | '/_authenticated/users/'
    | '/workspace-preview/forms/'
    | '/_authenticated/fleet/trucks/'
    | '/_authenticated/inventory/products/'
    | '/_authenticated/inventory/warehouses/'
    | '/_authenticated/users/collaborators/'
    | '/_authenticated/users/invitations/'
    | '/_authenticated/users/list/'
    | '/_authenticated/users/permission-profiles/'
    | '/workspace-preview/forms/collaborators/'
    | '/workspace-preview/forms/companies/'
    | '/workspace-preview/forms/customers/'
    | '/workspace-preview/forms/drivers/'
    | '/workspace-preview/forms/permission-profiles/'
    | '/workspace-preview/forms/products/'
    | '/workspace-preview/forms/trucks/'
    | '/workspace-preview/forms/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  WorkspacePreviewFormsRouteRoute: typeof WorkspacePreviewFormsRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  WorkspacePreviewIndexRoute: typeof WorkspacePreviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-preview/': {
      id: '/workspace-preview/'
      path: '/workspace-preview'
      fullPath: '/workspace-preview/'
      preLoaderRoute: typeof WorkspacePreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/workspace-preview/forms': {
      id: '/workspace-preview/forms'
      path: '/workspace-preview/forms'
      fullPath: '/workspace-preview/forms'
      preLoaderRoute: typeof WorkspacePreviewFormsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-preview/forms/': {
      id: '/workspace-preview/forms/'
      path: '/'
      fullPath: '/workspace-preview/forms/'
      preLoaderRoute: typeof WorkspacePreviewFormsIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences/': {
      id: '/_authenticated/preferences/'
      path: '/preferences'
      fullPath: '/preferences/'
      preLoaderRoute: typeof AuthenticatedPreferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview/': {
      id: '/_authenticated/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof AuthenticatedOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/workspace-preview/forms/warehouses/': {
      id: '/workspace-preview/forms/warehouses/'
      path: '/warehouses'
      fullPath: '/workspace-preview/forms/warehouses/'
      preLoaderRoute: typeof WorkspacePreviewFormsWarehousesIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/workspace-preview/forms/trucks/': {
      id: '/workspace-preview/forms/trucks/'
      path: '/trucks'
      fullPath: '/workspace-preview/forms/trucks/'
      preLoaderRoute: typeof WorkspacePreviewFormsTrucksIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/workspace-preview/forms/products/': {
      id: '/workspace-preview/forms/products/'
      path: '/products'
      fullPath: '/workspace-preview/forms/products/'
      preLoaderRoute: typeof WorkspacePreviewFormsProductsIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/workspace-preview/forms/permission-profiles/': {
      id: '/workspace-preview/forms/permission-profiles/'
      path: '/permission-profiles'
      fullPath: '/workspace-preview/forms/permission-profiles/'
      preLoaderRoute: typeof WorkspacePreviewFormsPermissionProfilesIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/workspace-preview/forms/drivers/': {
      id: '/workspace-preview/forms/drivers/'
      path: '/drivers'
      fullPath: '/workspace-preview/forms/drivers/'
      preLoaderRoute: typeof WorkspacePreviewFormsDriversIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/workspace-preview/forms/customers/': {
      id: '/workspace-preview/forms/customers/'
      path: '/customers'
      fullPath: '/workspace-preview/forms/customers/'
      preLoaderRoute: typeof WorkspacePreviewFormsCustomersIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/workspace-preview/forms/companies/': {
      id: '/workspace-preview/forms/companies/'
      path: '/companies'
      fullPath: '/workspace-preview/forms/companies/'
      preLoaderRoute: typeof WorkspacePreviewFormsCompaniesIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/workspace-preview/forms/collaborators/': {
      id: '/workspace-preview/forms/collaborators/'
      path: '/collaborators'
      fullPath: '/workspace-preview/forms/collaborators/'
      preLoaderRoute: typeof WorkspacePreviewFormsCollaboratorsIndexRouteImport
      parentRoute: typeof WorkspacePreviewFormsRouteRoute
    }
    '/_authenticated/users/permission-profiles/': {
      id: '/_authenticated/users/permission-profiles/'
      path: '/users/permission-profiles'
      fullPath: '/users/permission-profiles/'
      preLoaderRoute: typeof AuthenticatedUsersPermissionProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/list/': {
      id: '/_authenticated/users/list/'
      path: '/users/list'
      fullPath: '/users/list/'
      preLoaderRoute: typeof AuthenticatedUsersListIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/invitations/': {
      id: '/_authenticated/users/invitations/'
      path: '/users/invitations'
      fullPath: '/users/invitations/'
      preLoaderRoute: typeof AuthenticatedUsersInvitationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/collaborators/': {
      id: '/_authenticated/users/collaborators/'
      path: '/users/collaborators'
      fullPath: '/users/collaborators/'
      preLoaderRoute: typeof AuthenticatedUsersCollaboratorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/warehouses/': {
      id: '/_authenticated/inventory/warehouses/'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses/'
      preLoaderRoute: typeof AuthenticatedInventoryWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/products/': {
      id: '/_authenticated/inventory/products/'
      path: '/inventory/products'
      fullPath: '/inventory/products/'
      preLoaderRoute: typeof AuthenticatedInventoryProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet/trucks/': {
      id: '/_authenticated/fleet/trucks/'
      path: '/fleet/trucks'
      fullPath: '/fleet/trucks/'
      preLoaderRoute: typeof AuthenticatedFleetTrucksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedOverviewIndexRoute: typeof AuthenticatedOverviewIndexRoute
  AuthenticatedPreferencesIndexRoute: typeof AuthenticatedPreferencesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedFleetTrucksIndexRoute: typeof AuthenticatedFleetTrucksIndexRoute
  AuthenticatedInventoryProductsIndexRoute: typeof AuthenticatedInventoryProductsIndexRoute
  AuthenticatedInventoryWarehousesIndexRoute: typeof AuthenticatedInventoryWarehousesIndexRoute
  AuthenticatedUsersCollaboratorsIndexRoute: typeof AuthenticatedUsersCollaboratorsIndexRoute
  AuthenticatedUsersInvitationsIndexRoute: typeof AuthenticatedUsersInvitationsIndexRoute
  AuthenticatedUsersListIndexRoute: typeof AuthenticatedUsersListIndexRoute
  AuthenticatedUsersPermissionProfilesIndexRoute: typeof AuthenticatedUsersPermissionProfilesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedOverviewIndexRoute: AuthenticatedOverviewIndexRoute,
  AuthenticatedPreferencesIndexRoute: AuthenticatedPreferencesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedFleetTrucksIndexRoute: AuthenticatedFleetTrucksIndexRoute,
  AuthenticatedInventoryProductsIndexRoute:
    AuthenticatedInventoryProductsIndexRoute,
  AuthenticatedInventoryWarehousesIndexRoute:
    AuthenticatedInventoryWarehousesIndexRoute,
  AuthenticatedUsersCollaboratorsIndexRoute:
    AuthenticatedUsersCollaboratorsIndexRoute,
  AuthenticatedUsersInvitationsIndexRoute:
    AuthenticatedUsersInvitationsIndexRoute,
  AuthenticatedUsersListIndexRoute: AuthenticatedUsersListIndexRoute,
  AuthenticatedUsersPermissionProfilesIndexRoute:
    AuthenticatedUsersPermissionProfilesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface WorkspacePreviewFormsRouteRouteChildren {
  WorkspacePreviewFormsIndexRoute: typeof WorkspacePreviewFormsIndexRoute
  WorkspacePreviewFormsCollaboratorsIndexRoute: typeof WorkspacePreviewFormsCollaboratorsIndexRoute
  WorkspacePreviewFormsCompaniesIndexRoute: typeof WorkspacePreviewFormsCompaniesIndexRoute
  WorkspacePreviewFormsCustomersIndexRoute: typeof WorkspacePreviewFormsCustomersIndexRoute
  WorkspacePreviewFormsDriversIndexRoute: typeof WorkspacePreviewFormsDriversIndexRoute
  WorkspacePreviewFormsPermissionProfilesIndexRoute: typeof WorkspacePreviewFormsPermissionProfilesIndexRoute
  WorkspacePreviewFormsProductsIndexRoute: typeof WorkspacePreviewFormsProductsIndexRoute
  WorkspacePreviewFormsTrucksIndexRoute: typeof WorkspacePreviewFormsTrucksIndexRoute
  WorkspacePreviewFormsWarehousesIndexRoute: typeof WorkspacePreviewFormsWarehousesIndexRoute
}

const WorkspacePreviewFormsRouteRouteChildren: WorkspacePreviewFormsRouteRouteChildren =
  {
    WorkspacePreviewFormsIndexRoute: WorkspacePreviewFormsIndexRoute,
    WorkspacePreviewFormsCollaboratorsIndexRoute:
      WorkspacePreviewFormsCollaboratorsIndexRoute,
    WorkspacePreviewFormsCompaniesIndexRoute:
      WorkspacePreviewFormsCompaniesIndexRoute,
    WorkspacePreviewFormsCustomersIndexRoute:
      WorkspacePreviewFormsCustomersIndexRoute,
    WorkspacePreviewFormsDriversIndexRoute:
      WorkspacePreviewFormsDriversIndexRoute,
    WorkspacePreviewFormsPermissionProfilesIndexRoute:
      WorkspacePreviewFormsPermissionProfilesIndexRoute,
    WorkspacePreviewFormsProductsIndexRoute:
      WorkspacePreviewFormsProductsIndexRoute,
    WorkspacePreviewFormsTrucksIndexRoute:
      WorkspacePreviewFormsTrucksIndexRoute,
    WorkspacePreviewFormsWarehousesIndexRoute:
      WorkspacePreviewFormsWarehousesIndexRoute,
  }

const WorkspacePreviewFormsRouteRouteWithChildren =
  WorkspacePreviewFormsRouteRoute._addFileChildren(
    WorkspacePreviewFormsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  WorkspacePreviewFormsRouteRoute: WorkspacePreviewFormsRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  WorkspacePreviewIndexRoute: WorkspacePreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
