/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as WorkspacePreviewIndexRouteImport } from './routes/workspace-preview/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPreferencesIndexRouteImport } from './routes/_authenticated/preferences/index'
import { Route as AuthenticatedOverviewIndexRouteImport } from './routes/_authenticated/overview/index'
import { Route as AuthenticatedUsersListIndexRouteImport } from './routes/_authenticated/users/list/index'
import { Route as AuthenticatedUsersInvitationsIndexRouteImport } from './routes/_authenticated/users/invitations/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacePreviewIndexRoute = WorkspacePreviewIndexRouteImport.update({
  id: '/workspace-preview/',
  path: '/workspace-preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreferencesIndexRoute =
  AuthenticatedPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewIndexRoute =
  AuthenticatedOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersListIndexRoute =
  AuthenticatedUsersListIndexRouteImport.update({
    id: '/users/list/',
    path: '/users/list/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersInvitationsIndexRoute =
  AuthenticatedUsersInvitationsIndexRouteImport.update({
    id: '/users/invitations/',
    path: '/users/invitations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/workspace-preview/': typeof WorkspacePreviewIndexRoute
  '/overview/': typeof AuthenticatedOverviewIndexRoute
  '/preferences/': typeof AuthenticatedPreferencesIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/users/invitations/': typeof AuthenticatedUsersInvitationsIndexRoute
  '/users/list/': typeof AuthenticatedUsersListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginIndexRoute
  '/workspace-preview': typeof WorkspacePreviewIndexRoute
  '/overview': typeof AuthenticatedOverviewIndexRoute
  '/preferences': typeof AuthenticatedPreferencesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/users/invitations': typeof AuthenticatedUsersInvitationsIndexRoute
  '/users/list': typeof AuthenticatedUsersListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/workspace-preview/': typeof WorkspacePreviewIndexRoute
  '/_authenticated/overview/': typeof AuthenticatedOverviewIndexRoute
  '/_authenticated/preferences/': typeof AuthenticatedPreferencesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/users/invitations/': typeof AuthenticatedUsersInvitationsIndexRoute
  '/_authenticated/users/list/': typeof AuthenticatedUsersListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/workspace-preview/'
    | '/overview/'
    | '/preferences/'
    | '/profile/'
    | '/users/'
    | '/users/invitations/'
    | '/users/list/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/workspace-preview'
    | '/overview'
    | '/preferences'
    | '/profile'
    | '/users'
    | '/users/invitations'
    | '/users/list'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/login/'
    | '/workspace-preview/'
    | '/_authenticated/overview/'
    | '/_authenticated/preferences/'
    | '/_authenticated/profile/'
    | '/_authenticated/users/'
    | '/_authenticated/users/invitations/'
    | '/_authenticated/users/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  WorkspacePreviewIndexRoute: typeof WorkspacePreviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-preview/': {
      id: '/workspace-preview/'
      path: '/workspace-preview'
      fullPath: '/workspace-preview/'
      preLoaderRoute: typeof WorkspacePreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences/': {
      id: '/_authenticated/preferences/'
      path: '/preferences'
      fullPath: '/preferences/'
      preLoaderRoute: typeof AuthenticatedPreferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview/': {
      id: '/_authenticated/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof AuthenticatedOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/list/': {
      id: '/_authenticated/users/list/'
      path: '/users/list'
      fullPath: '/users/list/'
      preLoaderRoute: typeof AuthenticatedUsersListIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/invitations/': {
      id: '/_authenticated/users/invitations/'
      path: '/users/invitations'
      fullPath: '/users/invitations/'
      preLoaderRoute: typeof AuthenticatedUsersInvitationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOverviewIndexRoute: typeof AuthenticatedOverviewIndexRoute
  AuthenticatedPreferencesIndexRoute: typeof AuthenticatedPreferencesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedUsersInvitationsIndexRoute: typeof AuthenticatedUsersInvitationsIndexRoute
  AuthenticatedUsersListIndexRoute: typeof AuthenticatedUsersListIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOverviewIndexRoute: AuthenticatedOverviewIndexRoute,
  AuthenticatedPreferencesIndexRoute: AuthenticatedPreferencesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedUsersInvitationsIndexRoute:
    AuthenticatedUsersInvitationsIndexRoute,
  AuthenticatedUsersListIndexRoute: AuthenticatedUsersListIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  WorkspacePreviewIndexRoute: WorkspacePreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
