/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as WorkspacePreviewIndexRouteImport } from './routes/workspace-preview/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as WorkspacePreviewSandboxIndexRouteImport } from './routes/workspace-preview/sandbox/index'
import { Route as WorkspacePreviewBarbershopSetupIndexRouteImport } from './routes/workspace-preview/barbershop-setup/index'
import { Route as WorkspacePreviewAgendaIndexRouteImport } from './routes/workspace-preview/agenda/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPreferencesIndexRouteImport } from './routes/_authenticated/preferences/index'
import { Route as AuthenticatedOverviewIndexRouteImport } from './routes/_authenticated/overview/index'
import { Route as AuthenticatedAgendaIndexRouteImport } from './routes/_authenticated/agenda/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacePreviewIndexRoute = WorkspacePreviewIndexRouteImport.update({
  id: '/workspace-preview/',
  path: '/workspace-preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WorkspacePreviewSandboxIndexRoute =
  WorkspacePreviewSandboxIndexRouteImport.update({
    id: '/workspace-preview/sandbox/',
    path: '/workspace-preview/sandbox/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacePreviewBarbershopSetupIndexRoute =
  WorkspacePreviewBarbershopSetupIndexRouteImport.update({
    id: '/workspace-preview/barbershop-setup/',
    path: '/workspace-preview/barbershop-setup/',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspacePreviewAgendaIndexRoute =
  WorkspacePreviewAgendaIndexRouteImport.update({
    id: '/workspace-preview/agenda/',
    path: '/workspace-preview/agenda/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPreferencesIndexRoute =
  AuthenticatedPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewIndexRoute =
  AuthenticatedOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaIndexRoute =
  AuthenticatedAgendaIndexRouteImport.update({
    id: '/agenda/',
    path: '/agenda/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/workspace-preview/': typeof WorkspacePreviewIndexRoute
  '/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/overview/': typeof AuthenticatedOverviewIndexRoute
  '/preferences/': typeof AuthenticatedPreferencesIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/workspace-preview/agenda/': typeof WorkspacePreviewAgendaIndexRoute
  '/workspace-preview/barbershop-setup/': typeof WorkspacePreviewBarbershopSetupIndexRoute
  '/workspace-preview/sandbox/': typeof WorkspacePreviewSandboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/workspace-preview': typeof WorkspacePreviewIndexRoute
  '/agenda': typeof AuthenticatedAgendaIndexRoute
  '/overview': typeof AuthenticatedOverviewIndexRoute
  '/preferences': typeof AuthenticatedPreferencesIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/workspace-preview/agenda': typeof WorkspacePreviewAgendaIndexRoute
  '/workspace-preview/barbershop-setup': typeof WorkspacePreviewBarbershopSetupIndexRoute
  '/workspace-preview/sandbox': typeof WorkspacePreviewSandboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/workspace-preview/': typeof WorkspacePreviewIndexRoute
  '/_authenticated/agenda/': typeof AuthenticatedAgendaIndexRoute
  '/_authenticated/overview/': typeof AuthenticatedOverviewIndexRoute
  '/_authenticated/preferences/': typeof AuthenticatedPreferencesIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/workspace-preview/agenda/': typeof WorkspacePreviewAgendaIndexRoute
  '/workspace-preview/barbershop-setup/': typeof WorkspacePreviewBarbershopSetupIndexRoute
  '/workspace-preview/sandbox/': typeof WorkspacePreviewSandboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/workspace-preview/'
    | '/agenda/'
    | '/overview/'
    | '/preferences/'
    | '/profile/'
    | '/workspace-preview/agenda/'
    | '/workspace-preview/barbershop-setup/'
    | '/workspace-preview/sandbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/workspace-preview'
    | '/agenda'
    | '/overview'
    | '/preferences'
    | '/profile'
    | '/workspace-preview/agenda'
    | '/workspace-preview/barbershop-setup'
    | '/workspace-preview/sandbox'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/workspace-preview/'
    | '/_authenticated/agenda/'
    | '/_authenticated/overview/'
    | '/_authenticated/preferences/'
    | '/_authenticated/profile/'
    | '/workspace-preview/agenda/'
    | '/workspace-preview/barbershop-setup/'
    | '/workspace-preview/sandbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  WorkspacePreviewIndexRoute: typeof WorkspacePreviewIndexRoute
  WorkspacePreviewAgendaIndexRoute: typeof WorkspacePreviewAgendaIndexRoute
  WorkspacePreviewBarbershopSetupIndexRoute: typeof WorkspacePreviewBarbershopSetupIndexRoute
  WorkspacePreviewSandboxIndexRoute: typeof WorkspacePreviewSandboxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-preview/': {
      id: '/workspace-preview/'
      path: '/workspace-preview'
      fullPath: '/workspace-preview/'
      preLoaderRoute: typeof WorkspacePreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/workspace-preview/sandbox/': {
      id: '/workspace-preview/sandbox/'
      path: '/workspace-preview/sandbox'
      fullPath: '/workspace-preview/sandbox/'
      preLoaderRoute: typeof WorkspacePreviewSandboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-preview/barbershop-setup/': {
      id: '/workspace-preview/barbershop-setup/'
      path: '/workspace-preview/barbershop-setup'
      fullPath: '/workspace-preview/barbershop-setup/'
      preLoaderRoute: typeof WorkspacePreviewBarbershopSetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-preview/agenda/': {
      id: '/workspace-preview/agenda/'
      path: '/workspace-preview/agenda'
      fullPath: '/workspace-preview/agenda/'
      preLoaderRoute: typeof WorkspacePreviewAgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences/': {
      id: '/_authenticated/preferences/'
      path: '/preferences'
      fullPath: '/preferences/'
      preLoaderRoute: typeof AuthenticatedPreferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview/': {
      id: '/_authenticated/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof AuthenticatedOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda/': {
      id: '/_authenticated/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AuthenticatedAgendaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgendaIndexRoute: typeof AuthenticatedAgendaIndexRoute
  AuthenticatedOverviewIndexRoute: typeof AuthenticatedOverviewIndexRoute
  AuthenticatedPreferencesIndexRoute: typeof AuthenticatedPreferencesIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgendaIndexRoute: AuthenticatedAgendaIndexRoute,
  AuthenticatedOverviewIndexRoute: AuthenticatedOverviewIndexRoute,
  AuthenticatedPreferencesIndexRoute: AuthenticatedPreferencesIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  WorkspacePreviewIndexRoute: WorkspacePreviewIndexRoute,
  WorkspacePreviewAgendaIndexRoute: WorkspacePreviewAgendaIndexRoute,
  WorkspacePreviewBarbershopSetupIndexRoute:
    WorkspacePreviewBarbershopSetupIndexRoute,
  WorkspacePreviewSandboxIndexRoute: WorkspacePreviewSandboxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
